### ISSUE TITLE
Adding and replacing in delegation responses

### ISSUE THREAD

**Issue by paulehoffman** [bemasc/ds-glue#2]
Section 3.2 says: `The resolver SHALL add each of these reconstructed RRSets to the delegation responses, replacing any RRSet with the same owner name and type.` It feels wrong to say that the resolver changes the delegation response: the response is just a response. For example, a resolver that is logging responses should not alter what it logs based on the reconstructed RRSets. 

Should this instead talk about filling the resolver's cache? Does it add to the cache, and replace cached entries, from the reconstructed RRsets? Getting the DS data is a step before the resolver looks in its cache to determine what to do for its next step (possibly using secure transport for the following query).

**Comment by bemasc** [comment]
My impression is that resolvers are under no obligation to cache anything, especially glue records, so I'd like to avoid using that framing.  I've added more detail to the description in #3; please review.

**Comment by paulehoffman** [comment]
Agree that #3 addresses this, so am closing.
